// SPDX-License-Identifier: MIT OR Apache-2.0
//! The fixed JavaScript runtime that every generated glue module carries.
//!
//! This is the part of the output that does not depend on the descriptors: the
//! preamble (heap, string/byte marshalling, closures, timers, the async
//! executor bridge) and the `instantiate`/`setInstance` entry points, plus the
//! worker bootstrap used by shared-memory (`+atomics`) builds.

use super::js_string;
use crate::wasm::MemoryImport;

pub(super) const PREAMBLE: &str = "\
// Generated by wasm_lite_codegen — do not edit.
let __wl_memory;
let __wl_instance;
// The compiled module, kept so spawned threads (Web Workers) can reuse it.
let __wl_module;
// True when linear memory is a SharedArrayBuffer (an `+atomics` shared-memory
// build). TextDecoder rejects shared-backed views, so we copy before decoding.
let __wl_shared = false;

// Decode `len` UTF-8 bytes at `ptr` from the module's linear memory. A fresh
// view is taken each call so it stays valid if the module grows its memory.
function __wl_str(ptr, len) {
    const __view = new Uint8Array(__wl_memory.buffer, ptr, len);
    return new TextDecoder(\"utf-8\").decode(__wl_shared ? __view.slice() : __view);
}

// Copy a JS string into wasm memory for an export argument; returns [ptr, len].
// The caller frees it with __wl_free after the call.
function __wl_pass_str(s) {
    const bytes = new TextEncoder().encode(s);
    const ptr = __wl_instance.exports.__wl_malloc(bytes.length);
    new Uint8Array(__wl_memory.buffer, ptr, bytes.length).set(bytes);
    return [ptr, bytes.length];
}

// Copy bytes into wasm memory for an export argument; returns [ptr, len]. Accepts
// a Uint8Array (or anything Uint8Array's constructor coerces, e.g. a number[]).
function __wl_pass_bytes(a) {
    const bytes = a instanceof Uint8Array ? a : new Uint8Array(a);
    const ptr = __wl_instance.exports.__wl_malloc(bytes.length);
    new Uint8Array(__wl_memory.buffer, ptr, bytes.length).set(bytes);
    return [ptr, bytes.length];
}

// Value table: opaque handles to JS values. Rust holds an index; the table
// holds the real object. Freed slots are reused.
//
// The first four slots are permanently the JS singletons, so Rust can name
// them as constants and passing one costs no table churn. __wl_drop ignores
// them; they are never on the free list.
const __wl_heap = [undefined, null, true, false];
const __wl_free = [];
function __wl_add(value) {
    const idx = __wl_free.length > 0 ? __wl_free.pop() : __wl_heap.length;
    __wl_heap[idx] = value;
    return idx;
}
function __wl_obj(idx) {
    return __wl_heap[idx];
}
function __wl_drop(idx) {
    if (idx < 4) return;   // a reserved singleton
    __wl_heap[idx] = undefined;
    __wl_free.push(idx);
}
// A second, independently-owned handle to the same JS value. The table holds
// references, so this is a slot allocation, not a copy of the object.
function __wl_clone(idx) {
    return __wl_add(__wl_heap[idx]);
}
// Handles to primitive JS values. `kind` picks null/undefined/true/false so one
// import covers the four singletons.
function __wl_num(v) { return __wl_add(v); }
// A wasm i64 param is already a BigInt on this side.
function __wl_bigint(v) { return __wl_add(v); }
function __wl_ubigint(v) { return __wl_add(BigInt.asUintN(64, v)); }
// Wider than 64 bits: the value arrives as decimal text, since no wasm
// parameter can carry it.
function __wl_bigint_str(ptr, len) { return __wl_add(BigInt(__wl_str(ptr, len))); }

function __wl_str_val(ptr, len) { return __wl_add(__wl_str(ptr, len)); }
// A handle to the module's linear memory object, which threading polyfills
// need to hand to a worker.
function __wl_memory_obj() { return __wl_add(__wl_memory); }
// The compiled module, which a thread spawner passes to a worker.
function __wl_module_obj() { return __wl_add(__wl_module); }
// JS strict equality between two handles.
function __wl_eq(a, b) { return __wl_heap[a] === __wl_heap[b] ? 1 : 0; }
// JS operators on the values two handles denote. One import with an opcode
// rather than a dozen imports, since they differ only in the operator.
function __wl_binop(op, a, b) {
    const x = __wl_heap[a], y = __wl_heap[b];
    switch (op) {
        case 0: return __wl_add(x + y);
        case 1: return __wl_add(x - y);
        case 2: return __wl_add(x * y);
        case 3: return __wl_add(x / y);
        case 4: return __wl_add(x % y);
        case 5: return __wl_add(x & y);
        case 6: return __wl_add(x | y);
        case 7: return __wl_add(x ^ y);
        case 8: return __wl_add(x << y);
        case 9: return __wl_add(x >> y);
        case 10: return __wl_add(x >>> y);
        default: return __wl_add(x ** y);
    }
}
// Three-way comparison. 2 means unordered, which is what JS gives for NaN and
// for values whose coercion does not compare.
function __wl_cmp(a, b) {
    const x = __wl_heap[a], y = __wl_heap[b];
    if (x < y) return -1;
    if (x > y) return 1;
    if (x == y) return 0;
    return 2;
}
// JS type predicates, by opcode.
function __wl_is(kind, a) {
    const x = __wl_heap[a];
    switch (kind) {
        case 0: return typeof x === \"object\" && x !== null ? 1 : 0;
        case 1: return typeof x === \"function\" ? 1 : 0;
        case 2: return typeof x === \"string\" ? 1 : 0;
        case 3: return x === null ? 1 : 0;
        case 4: return x === undefined ? 1 : 0;
        case 5: return x ? 1 : 0;
        case 6: return typeof x === \"bigint\" ? 1 : 0;
        default: return typeof x === \"symbol\" ? 1 : 0;
    }
}
// `/` that hands back whatever it throws instead of propagating — BigInt
// division by zero raises RangeError, and js-sys reports that as a value.
// The decimal text of a numeric handle. Text rather than a wasm parameter
// because the same path has to serve i64 through u128, and no parameter is
// wide enough for the latter.
function __wl_num_str(idx, out) {
    const v = __wl_heap[idx];
    if (typeof v !== \"bigint\" && typeof v !== \"number\") return 0;
    const b = new TextEncoder().encode(String(v));
    const p = __wl_instance.exports.__wl_malloc(b.length);
    new Uint8Array(__wl_memory.buffer, p, b.length).set(b);
    const dv = new DataView(__wl_memory.buffer);
    dv.setUint32(out, p, true);
    dv.setUint32(out + 4, b.length, true);
    return 1;
}
function __wl_checked_div(a, b) {
    try { return __wl_add(__wl_heap[a] / __wl_heap[b]); }
    catch (e) { return __wl_add(e); }
}
function __wl_unop(op, a) {
    const x = __wl_heap[a];
    switch (op) {
        case 0: return __wl_add(-x);
        case 1: return __wl_add(!x);
        default: return __wl_add(~x);
    }
}
// Reading a primitive back out of a handle. Each returns 1/0 for present/absent
// and writes the value through `out`, so a genuine NaN or empty string is not
// confused with the wrong type. A fresh DataView per call: a malloc in between
// can grow memory and detach an older one.
function __wl_as_f64(idx, out) {
    const v = __wl_heap[idx];
    if (typeof v !== \"number\") return 0;
    new DataView(__wl_memory.buffer).setFloat64(out, v, true);
    return 1;
}
function __wl_as_bool(idx, out) {
    const v = __wl_heap[idx];
    if (typeof v !== \"boolean\") return 0;
    new DataView(__wl_memory.buffer).setInt32(out, v ? 1 : 0, true);
    return 1;
}
function __wl_as_str(idx, out) {
    const v = __wl_heap[idx];
    if (typeof v !== \"string\") return 0;
    const b = new TextEncoder().encode(v);
    const p = __wl_instance.exports.__wl_malloc(b.length);
    new Uint8Array(__wl_memory.buffer, p, b.length).set(b);
    const dv = new DataView(__wl_memory.buffer);
    dv.setUint32(out, p, true);
    dv.setUint32(out + 4, b.length, true);
    return 1;
}

// Async executor support. Drive one executor turn; a panic in a polled task
// traps here, which we turn into a test failure (fail-closed) rather than an
// uncaught error in a timer/microtask callback.
function __wl_tick() {
    try {
        __wl_instance.exports.__wl_async_tick();
    } catch (e) {
        globalThis.__wl_done = { ok: false, error: String((e && e.stack) || e) };
    }
}
// __wl_schedule kicks one event-loop turn; only called when the module uses
// `spawn_local`.
function __wl_schedule() {
    setTimeout(__wl_tick, 0);
}

// Sleep the executor until a Waker bumps the wake atom. `Atomics.waitAsync`
// resolves on a `memory.atomic.notify` to `ptr` — including one from another
// worker — so cross-thread wakes reach the main thread without busy-polling.
function __wl_wait_async(ptr, expected) {
    if (typeof Atomics.waitAsync === \"function\") {
        const r = Atomics.waitAsync(new Int32Array(__wl_memory.buffer), ptr >>> 2, expected);
        if (r.async) { r.value.then(__wl_tick); return; }
    }
    // No waitAsync, or the value already changed (\"not-equal\"): re-poll soon.
    setTimeout(__wl_tick, 0);
}

// Cancellable Rust timers. A normal wasm module owns its timers in this realm.
// A shared-memory worker proxies them to the root realm, whose event loop
// outlives the worker that created the future. The root consumes each token
// exactly once by calling either __wl_timer_fire or __wl_timer_cancelled.
const __wl_timers = new Map();
let __wl_timer_handle = null;
function __wl_timer_schedule() {
    if (__wl_timer_handle !== null) clearTimeout(__wl_timer_handle);
    __wl_timer_handle = null;
    if (__wl_timers.size === 0) return;
    let next = Infinity;
    for (const deadline of __wl_timers.values()) next = Math.min(next, deadline);
    __wl_timer_handle = setTimeout(__wl_timer_drain, Math.max(0, next - performance.now()));
}
function __wl_timer_drain() {
    __wl_timer_handle = null;
    const now = performance.now();
    const ready = [];
    for (const [token, deadline] of __wl_timers) {
        if (deadline <= now) {
            __wl_timers.delete(token);
            ready.push(token);
        }
    }
    __wl_timer_schedule();
    for (const token of ready) __wl_instance.exports.__wl_timer_fire(token);
}
function __wl_timer_arm_local(token, delay) {
    __wl_timers.set(token, performance.now() + Math.max(0, delay));
    __wl_timer_schedule();
}
function __wl_timer_cancel_local(token) {
    if (!__wl_timers.delete(token)) return;
    __wl_timer_schedule();
    __wl_instance.exports.__wl_timer_cancelled(token);
}
function __wl_timer_arm(token, delay) {
    if (__wl_shared && globalThis.__wl_spawned_worker === true) {
        self.postMessage({ __wl_timer_arm: [token, delay] });
    } else {
        __wl_timer_arm_local(token, delay);
    }
}
function __wl_timer_cancel(token) {
    if (__wl_shared && globalThis.__wl_spawned_worker === true) {
        self.postMessage({ __wl_timer_cancel: token });
    } else {
        __wl_timer_cancel_local(token);
    }
}

function __wl_spawn_unavailable(_work) {
    throw new Error(\"wasm_lite: thread::spawn requires a shared-memory +atomics build\");
}

// Fail-closed async-test verdict. The test body marks itself \"pending\" so the
// bootstrap won't declare success when `main` returns; the body signals pass
// when it actually completes. A panic in between fails via __wl_tick above, and
// a hang falls to the runner's timeout — so an async test can never pass by
// default.
function __wl_test_pending() { globalThis.__wl_async_pending = true; }
function __wl_test_pass() { globalThis.__wl_done = { ok: true, error: \"\" }; }

// Cross-realm log bridge. A worker is a separate JS realm, so its console output
// is invisible to the (headless) test runner, which only captures the main realm.
// Workers forward each console line up the spawn chain via postMessage; at the
// main realm it is replayed into the page's console (where the runner captures
// it). Keeps detached-worker panics from being silent on the CLI.
const __wl_is_worker = typeof WorkerGlobalScope !== \"undefined\" && self instanceof WorkerGlobalScope;
function __wl_sink_log(level, text) {
    if (__wl_is_worker) {
        self.postMessage({ __wl_log: [level, text] });   // relay up to our parent
    } else {
        (globalThis.console[level] || globalThis.console.log)(text);   // main: page captures it
    }
}

// A JS exception escaping a non-Result import unwinds the wasm frames without
// running Rust destructors or restoring the shadow stack pointer — the
// instance's state is as suspect as after a panic. Record the failure
// (fail-closed for tests), log it loudly, and rethrow; every further export
// call is refused via __wl_check_live. (Result-returning imports catch the
// exception and hand it to Rust instead — bind throwy JS as `Result<_, JsValue>`.)
let __wl_dead = null;
function __wl_fatal(e, name) {
    __wl_dead = \"imported JS function \" + name + \" threw: \" + String((e && e.stack) || e);
    __wl_sink_log(\"error\", \"wasm_lite: \" + __wl_dead + \" — the wasm instance is now unusable; bind the import as Result<_, JsValue> to handle JS exceptions instead\");
    if (!globalThis.__wl_done) globalThis.__wl_done = { ok: false, error: __wl_dead };
    throw e;
}
function __wl_check_live() {
    if (__wl_dead) throw new Error(\"wasm_lite: instance is unusable: \" + __wl_dead);
}

// Wrap a Rust closure as a JS function. `id` indexes a *Rust-side* registry,
// not a pointer: dropping the Closure removes the entry, so a JS reference that
// outlives it (an unregistered listener, say) calls a no-op instead of reading
// freed memory. Arity picks the trampoline; a one-argument closure takes
// ownership of its argument's table slot, matching the export convention.
function __wl_closure_new(id, arity) {
    let f;
    if (arity === 0) {
        f = () => { __wl_check_live(); __wl_instance.exports.__wl_closure_call_0(id); };
    } else if (arity === 1) {
        f = (a) => { __wl_check_live(); __wl_instance.exports.__wl_closure_call_1(id, __wl_add(a)); };
    } else {
        // Variadic: pack one table index per argument into a buffer wasm can
        // read. The Uint32Array view is taken *after* the malloc, which may
        // grow memory and detach any earlier view.
        f = function (...args) {
            __wl_check_live();
            const n = args.length;
            const ptr = __wl_instance.exports.__wl_malloc(n * 4);
            const view = new Uint32Array(__wl_memory.buffer, ptr, n);
            for (let i = 0; i < n; i++) view[i] = __wl_add(args[i]);
            const r = __wl_instance.exports.__wl_closure_call_n(id, n, ptr) >>> 0;
            __wl_instance.exports.__wl_free(ptr, n * 4);
            // 0 is: returned nothing. Otherwise the low bits are the handle
            // plus one, and the high bit means throw it rather than return it.
            if (r === 0) return undefined;
            const h = (r & 0x7fffffff) - 1;
            const out = __wl_obj(h);
            __wl_drop(h);
            if (r & 0x80000000) throw out;
            return out;
        };
    }
    return __wl_add(f);
}

";

/// The `instantiate`/`setInstance` exports for a module with its own (exported)
/// memory — the default case.
pub(super) const INSTANTIATE: &str = "
export async function instantiate(wasmUrl) {
    const { module, instance } = await WebAssembly.instantiateStreaming(fetch(wasmUrl), makeImports());
    __wl_module = module;
    __wl_instance = instance;
    __wl_memory = instance.exports.memory;
    return instance;
}

// Used by the interop loader, which instantiates the merged module itself and
// then hands us the instance.
export function setInstance(instance) {
    __wl_instance = instance;
    __wl_memory = instance.exports.memory;
}
";

/// The `instantiate`/`setInstance` exports for a module that *imports* a shared
/// memory (an `+atomics` `--import-memory` build). JS creates the
/// `WebAssembly.Memory` (or a worker passes in the one it received) and supplies
/// it as an import. `makeMemory()` is exported so a future thread spawner can
/// create the shared memory once and hand the same object to every worker.
pub(super) fn instantiate_shared(mem: &MemoryImport, worker_specifier: &str) -> String {
    let module = js_string(&mem.module);
    let name = js_string(&mem.name);
    let worker_specifier = js_string(worker_specifier);
    let maximum = mem
        .maximum
        .map_or(String::new(), |m| format!(", maximum: {m}"));
    let shared = mem.shared;
    format!(
        "
export function makeMemory() {{
    return new WebAssembly.Memory({{ initial: {initial}{maximum}, shared: {shared} }});
}}

export async function instantiate(wasmUrl, memory) {{
    __wl_memory = memory || makeMemory();
    __wl_shared = {shared};
    const imports = makeImports();
    imports[{module}] = imports[{module}] || Object.create(null);
    imports[{module}][{name}] = __wl_memory;
    const {{ module: m, instance }} = await WebAssembly.instantiateStreaming(fetch(wasmUrl), imports);
    __wl_module = m;
    __wl_instance = instance;
    return instance;
}}

// Used by the interop loader / a worker that already has the shared memory and
// the compiled module.
export function setInstance(instance, memory, module) {{
    __wl_instance = instance;
    __wl_memory = memory;
    __wl_module = module;
    __wl_shared = {shared};
}}

// Per-thread stack size for spawned workers.
const __WL_STACK = 1 << 20;
// Keep live workers referenced so they are not garbage-collected mid-run.
const __wl_workers = new Set();

// A worker that never starts is terminal, not slow: nothing will resolve the
// join that is waiting on it. Record the first such failure where the runner can
// see it, so a run ends with the reason instead of with a timeout that suggests
// raising the timeout. Still logged, so an interactive session sees it too.
function __wl_worker_start_failed(reason) {{
    const text = \"wasm_lite: worker failed to start: \" + reason;
    if (globalThis.__wl_worker_start_error === undefined) {{
        globalThis.__wl_worker_start_error = text;
    }}
    __wl_sink_log(\"error\", text);
}}

// Runtime import: spawn a Web Worker for the boxed closure `work`. Allocates a
// fresh stack + TLS block, then hands the worker this module + shared memory.
//
// The allocation happens on the calling thread (the memory is shared, so any
// thread's allocator serves), but the *worker creation* is delegated to the
// main thread whenever we are ourselves a worker. Chrome will not start a
// nested worker while its parent worker is blocked: the child's module script
// is fetched through the parent, and a parent sitting in `Atomics.wait` — which
// is what `join`, `park` and every blocking lock do — never services it. The
// child then never runs and the parent waits forever. (Firefox does not have
// this problem, which is why a Firefox-only CI never saw it.) Sending the
// request to the main thread, whose event loop is always turning, sidesteps it
// entirely and costs one postMessage.
function __wl_spawn(work) {{
    const stackPtr = __wl_instance.exports.__wl_thread_alloc(__WL_STACK);
    const tlsSize = __wl_instance.exports.__tls_size.value;
    const tlsPtr = tlsSize ? __wl_instance.exports.__wl_thread_alloc(tlsSize) : 0;
    __wl_spawn_at(work, stackPtr, tlsPtr, tlsSize);
}}

// Create the worker, or ask our creator to. Called with a stack and TLS block
// already allocated, so it is position-independent: whoever ends up running it
// hands the same pointers to the new thread.
//
// Because every worker takes this path, the main thread creates all of them —
// so a worker's creator is always the main thread and this is always one hop,
// never a chain. Rust-side nesting depth is unbounded; the messaging is flat.
function __wl_spawn_at(work, stackPtr, tlsPtr, tlsSize) {{
    if (__wl_is_worker) {{
        self.postMessage({{ __wl_spawn_req: [work, stackPtr, tlsPtr, tlsSize] }});
        return;
    }}
    globalThis.__wl_spawn_count = (globalThis.__wl_spawn_count || 0) + 1;
    const w = new Worker(new URL({worker_specifier}, import.meta.url), {{ type: \"module\" }});
    __wl_workers.add(w);
    // A worker that fails to start — a fetch the page's COEP rejects, a syntax
    // error in the bootstrap, a nested-worker restriction — reports through
    // `onerror` and nowhere else. Without this it is perfectly silent: the
    // spawn appears to succeed and the thread simply never runs.
    w.onerror = (e) => {{
        __wl_worker_start_failed(
            (e && (e.message || e.filename)) ? ((e.message || \"\") + \" @ \" + (e.filename || \"?\") + \":\" + (e.lineno || 0)) : String(e));
    }};
    w.onmessageerror = (e) => {{
        __wl_sink_log(\"error\", \"wasm_lite: spawned worker could not deserialize its start message \" +
            \"(a WebAssembly.Module or SharedArrayBuffer needs a cross-origin-isolated page): \" + String(e));
    }};
    w.onmessage = (e) => {{
        const m = e.data;
        if (m && m.__wl_log) {{ __wl_sink_log(m.__wl_log[0], m.__wl_log[1]); }}   // forward worker console up
        else if (m && m.__wl_start_failed !== undefined) {{ __wl_worker_start_failed(m.__wl_start_failed); }}
        // A thread this worker spawned: create it here (or relay further up).
        // Its stack and TLS are already allocated in the shared memory.
        else if (m && m.__wl_spawn_req) {{ __wl_spawn_at(...m.__wl_spawn_req); }}
        else if (m && m.__wl_timer_arm) {{ __wl_timer_arm_local(...m.__wl_timer_arm); }}
        else if (m && m.__wl_timer_cancel !== undefined) {{ __wl_timer_cancel_local(m.__wl_timer_cancel); }}
        else {{                                                                   // \"done\"
            globalThis.__wl_worker_done = (globalThis.__wl_worker_done || 0) + 1;
            __wl_workers.delete(w);
            w.terminate();
            // The worker cannot free the heap blocks backing its own wasm
            // stack or TLS: it would return through deallocated storage. Once
            // its completion message reaches this realm it is no longer
            // running wasm, so the shared allocator can release both safely.
            __wl_instance.exports.__wl_thread_free(stackPtr, __WL_STACK);
            if (tlsSize) __wl_instance.exports.__wl_thread_free(tlsPtr, tlsSize);
        }}
    }};
    w.postMessage({{
        module: __wl_module, memory: __wl_memory, work,
        stackPtr, stackTop: stackPtr + __WL_STACK, tlsPtr, tlsSize,
    }});
}}
",
        initial = mem.initial,
    )
}

/// Generate the worker bootstrap module for spawned threads.
///
/// `glue_specifier` is the module specifier the worker imports the glue from
/// (a sibling of the worker file, e.g. `"./program.js"`). The worker receives a
/// message with the compiled module, the shared memory, the boxed `work`
/// pointer, and a freshly allocated stack + TLS block; it instantiates the same
/// module on the same memory, points this thread's `__stack_pointer` at the new
/// stack, initializes TLS, runs the entry trampoline, then reports completion
/// and closes. The parent frees the stack and TLS after that report.
pub fn generate_worker(glue_specifier: &str) -> String {
    let glue = js_string(glue_specifier);
    format!(
        "// Generated by wasm_lite_codegen — worker bootstrap for spawned threads.
import {{ makeImports, setInstance }} from {glue};

// Runtime imports use this marker to proxy realm-bound services (notably
// timers) to the root shared-memory instance.
globalThis.__wl_spawned_worker = true;

// Forward this worker's console output to our parent so it reaches the main
// realm (and the test runner / CLI). Still log locally for browser devtools.
for (const __l of [\"log\", \"error\", \"warn\", \"info\"]) {{
    const __orig = console[__l] ? console[__l].bind(console) : function () {{}};
    console[__l] = (...a) => {{ __orig(...a); self.postMessage({{ __wl_log: [__l, a.join(\" \")] }}); }};
}}

// This handler is `async`, so anything it throws becomes an *unhandled
// rejection* — which does not reach the parent's `onerror` and is therefore
// invisible from the outside. These listeners are the only way a failure
// between \"worker started\" and \"closure running\" gets reported at all.
self.addEventListener(\"error\", (ev) => {{
    self.postMessage({{ __wl_log: [\"error\", \"wasm_lite: worker error: \" + (ev.message || ev)] }});
}});
self.addEventListener(\"unhandledrejection\", (ev) => {{
    const r = ev.reason;
    // Structured, not just logged: a thread that never started will never
    // resolve its join, so the runner has to be able to tell this apart from
    // \"still working\" rather than sitting out its whole timeout.
    self.postMessage({{ __wl_start_failed: String((r && (r.stack || r.message)) || r) }});
}});

self.onmessage = async (e) => {{
    const {{ module, memory, work, stackPtr, stackTop, tlsPtr, tlsSize }} = e.data;
    const imports = makeImports();
    imports[\"env\"] = imports[\"env\"] || {{}};
    imports[\"env\"][\"memory\"] = memory;
    const instance = await WebAssembly.instantiate(module, imports);
    setInstance(instance, memory, module);
    // These are linker-generated and only exported on request. Without this
    // check the next line is a bare \"cannot set properties of undefined\",
    // pointing at generated code rather than at the missing link flag.
    for (const __s of [\"__stack_pointer\", \"__wasm_init_tls\"]) {{
        if (instance.exports[__s] === undefined) {{
            throw new Error(\"wasm_lite: this module does not export `\" + __s +
                \"`; build it with -C link-arg=--export=\" + __s +
                \" (in rustdocflags too, for doctests)\");
        }}
    }}
    // Give this thread its own stack and TLS, then run the closure.
    instance.exports.__stack_pointer.value = stackTop;
    if (tlsSize) instance.exports.__wasm_init_tls(tlsPtr);

    const finish = () => {{
        // The parent owns teardown. Freeing these here would deallocate the
        // stack this callback returns through (and this realm's active TLS).
        self.postMessage(\"done\");
        self.close();
    }};

    // A panic traps the instance; its state is suspect, so tear down at once
    // (the panic was already logged + routed to any joiner).
    let panicked = false;
    try {{
        instance.exports.__wl_thread_entry(work);
    }} catch (_e) {{
        panicked = true;
    }}

    // Drain the event-loop executor before teardown: if the closure called
    // `spawn_local`, its tasks live in this thread's TLS and are still pending —
    // freeing now would drop them and free the TLS underneath them. Wait until
    // the executor is idle (it self-drives via the scheduler), then tear down.
    const idle = instance.exports.__wl_executor_idle;
    if (panicked || !idle || idle()) {{
        finish();
    }} else {{
        (function drain() {{ idle() ? finish() : setTimeout(drain, 0); }})();
    }}
}};
"
    )
}
