// SPDX-License-Identifier: MIT OR Apache-2.0
//! `wasm_lite build`: generate the JavaScript glue for a compiled wasm_lite module.
//!
//! Usage:
//!     wasm_lite build <input.wasm>            # write glue to stdout
//!     wasm_lite build <input.wasm> -o out.js  # write glue to a file

use std::ffi::OsString;
use std::io::{ErrorKind, Write as _};
use std::path::{Path, PathBuf};
use std::process::exit;
use std::sync::atomic::{AtomicU64, Ordering};

const GENERATED_MARKER: &str = "// Generated by wasm_lite_codegen";
static NEXT_TEMP_FILE: AtomicU64 = AtomicU64::new(0);

const USAGE: &str = "usage: wasm_lite build <input.wasm> [-o <output.js>]\n\
                     \n\
                     Generates the JavaScript glue for a compiled wasm_lite module.\n\
                     With -o, a shared-memory module also writes a sibling\n\
                     <output>.worker.js module. wasm-bindgen interop modules\n\
                     write <output>.wasm, <output>.wl.js, and <output>.wb.js.\n\
                     \n\
                     options:\n\
                     \x20   -o, --output <path>   write the glue to <path> instead of stdout\n\
                     \x20   -h, --help            show this help";

pub fn main(argv: Vec<OsString>) {
    let args = match parse_args(argv) {
        Ok(Some(args)) => args,
        Ok(None) => {
            println!("{USAGE}");
            return;
        }
        Err(msg) => {
            eprintln!("{msg}");
            eprintln!("{USAGE}");
            exit(2);
        }
    };

    if let Err(err) = run(args) {
        eprintln!("error: {err}");
        exit(1);
    }
}

struct Args {
    input: PathBuf,
    output: Option<PathBuf>,
}

/// `Ok(None)` means help was requested.
fn parse_args(argv: Vec<OsString>) -> Result<Option<Args>, String> {
    let mut input = None;
    let mut output = None;
    let mut args = argv.into_iter();

    while let Some(arg) = args.next() {
        if arg == "-o" || arg == "--output" {
            let path = args.next().ok_or("missing path after -o")?;
            output = Some(PathBuf::from(path));
        } else if arg == "-h" || arg == "--help" {
            return Ok(None);
        } else if arg.to_string_lossy().starts_with('-') {
            // An unknown flag must not be mistaken for the input path —
            // `wasm_lite --helpp` should error, not "failed to read --helpp".
            return Err(format!("unknown option {:?}", arg.to_string_lossy()));
        } else if input.is_none() {
            input = Some(PathBuf::from(arg));
        } else {
            return Err("too many arguments".to_string());
        }
    }

    Ok(Some(Args {
        input: input.ok_or("missing input wasm path")?,
        output,
    }))
}

fn run(args: Args) -> Result<(), String> {
    let Args { input, output } = args;
    let wasm =
        std::fs::read(&input).map_err(|e| format!("failed to read {}: {e}", input.display()))?;

    // Before the interop branch: an interop module needs these too, and more of
    // them, and reaching the wasm-bindgen CLI first trades our message for its
    // `failed to find __tls_align`, which names a symbol but not the fix.
    let missing = wasm_lite_codegen::missing_thread_exports(&wasm)?;
    if !missing.is_empty() {
        return Err(wasm_lite_codegen::missing_thread_exports_message(&missing));
    }
    // Likewise for a module that can spawn but has nowhere to spawn into.
    if wasm_lite_codegen::spawns_without_shared_memory(&wasm)? {
        return Err(wasm_lite_codegen::spawns_without_shared_memory_message(
            &wasm,
        ));
    }

    if wasm_lite_codegen::uses_wasm_bindgen(&wasm) {
        let output = output
            .ok_or("wasm-bindgen interop emits multiple files and requires -o <output.js>")?;
        return write_interop_bundle(&input, &output);
    }

    let descriptors = wasm_lite_codegen::descriptors_from_wasm(&wasm)?;
    let exports = wasm_lite_codegen::exports_from_wasm(&wasm)?;
    let memory = wasm_lite_codegen::imported_memory(&wasm)?;

    match output {
        Some(path) => {
            let glue_name = utf8_file_name(&path)?.to_owned();
            let worker = memory.as_ref().filter(|memory| memory.shared).map(|_| {
                let worker_name = format!("{glue_name}.worker.js");
                let worker_path = path.with_file_name(&worker_name);
                let worker_specifier = module_specifier(&worker_name);
                (worker_path, worker_specifier)
            });
            let worker_specifier = worker
                .as_ref()
                .map_or("./wl_worker.js", |(_, specifier)| specifier.as_str());
            let glue = wasm_lite_codegen::generate_glue_with_worker(
                &descriptors,
                &exports,
                memory.as_ref(),
                worker_specifier,
            );
            let mut artifacts = vec![Artifact::explicit(path, glue.into_bytes())];
            if let Some((worker_path, _)) = &worker {
                let worker = wasm_lite_codegen::generate_worker(&module_specifier(&glue_name));
                artifacts.push(Artifact::generated(
                    worker_path.clone(),
                    worker.into_bytes(),
                ));
            }
            write_artifacts(&artifacts)?;
            if let Some((worker_path, _)) = worker {
                eprintln!("wrote {} (thread worker bootstrap)", worker_path.display());
            }
        }
        None => {
            let glue = wasm_lite_codegen::generate_glue(&descriptors, &exports, memory.as_ref());
            write_stdout(glue.as_bytes())?;
        }
    }
    Ok(())
}

fn write_interop_bundle(input: &Path, output: &Path) -> Result<(), String> {
    let output_name = utf8_file_name(output)?;
    let wasm_name = format!("{output_name}.wasm");
    let wl_name = format!("{output_name}.wl.js");
    let wb_name = format!("{output_name}.wb.js");
    let wasm_path = output.with_file_name(&wasm_name);
    let wl_path = output.with_file_name(&wl_name);
    let wb_path = output.with_file_name(&wb_name);

    let mut bundle = wasm_lite_codegen::build_interop(input)?;
    bundle.loader_js = wasm_lite_codegen::interop_loader(
        &module_specifier(&wasm_name),
        &module_specifier(&wl_name),
        &module_specifier(&wb_name),
    );
    let artifacts = [
        Artifact::explicit(output.to_path_buf(), bundle.loader_js.into_bytes()),
        Artifact::explicit(wasm_path.clone(), bundle.wasm),
        Artifact::explicit(wl_path.clone(), bundle.wl_glue_js.into_bytes()),
        Artifact::explicit(wb_path.clone(), bundle.wb_glue_js.into_bytes()),
    ];
    write_artifacts(&artifacts)?;
    for path in [wasm_path, wl_path, wb_path] {
        eprintln!("wrote {} (wasm-bindgen interop artifact)", path.display());
    }
    Ok(())
}

fn write_stdout(contents: &[u8]) -> Result<(), String> {
    match std::io::stdout().lock().write_all(contents) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == ErrorKind::BrokenPipe => Ok(()),
        Err(error) => Err(format!("failed to write stdout: {error}")),
    }
}

fn utf8_file_name(path: &Path) -> Result<&str, String> {
    path.file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| format!("output path {} has no UTF-8 file name", path.display()))
}

fn module_specifier(file_name: &str) -> String {
    const HEX: &[u8; 16] = b"0123456789ABCDEF";
    let mut encoded = String::with_capacity(file_name.len() + 2);
    encoded.push_str("./");
    for byte in file_name.bytes() {
        if byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'.' | b'_' | b'~') {
            encoded.push(char::from(byte));
        } else {
            encoded.push('%');
            encoded.push(char::from(HEX[usize::from(byte >> 4)]));
            encoded.push(char::from(HEX[usize::from(byte & 0x0f)]));
        }
    }
    encoded
}

struct Artifact {
    path: PathBuf,
    contents: Vec<u8>,
    generated_only: bool,
}

impl Artifact {
    fn explicit(path: PathBuf, contents: Vec<u8>) -> Self {
        Self {
            path,
            contents,
            generated_only: false,
        }
    }

    fn generated(path: PathBuf, contents: Vec<u8>) -> Self {
        Self {
            path,
            contents,
            generated_only: true,
        }
    }
}

fn write_artifacts(artifacts: &[Artifact]) -> Result<(), String> {
    for (index, artifact) in artifacts.iter().enumerate() {
        if artifacts[..index]
            .iter()
            .any(|previous| previous.path == artifact.path)
        {
            return Err(format!(
                "refusing to write two generated artifacts to {}",
                artifact.path.display()
            ));
        }
        if artifact.generated_only {
            validate_generated_destination(&artifact.path)?;
        }
    }

    let mut pending = Vec::with_capacity(artifacts.len());
    for artifact in artifacts {
        let (temporary_path, mut file) = create_temporary_file(&artifact.path)?;
        if let Err(error) = file.write_all(&artifact.contents) {
            let _ = std::fs::remove_file(&temporary_path);
            remove_pending(&pending);
            return Err(format!(
                "failed to write temporary output for {}: {error}",
                artifact.path.display()
            ));
        }
        drop(file);
        pending.push((temporary_path, artifact.path.clone()));
    }

    while let Some((temporary_path, destination)) = pending.first().cloned() {
        if let Err(error) = std::fs::rename(&temporary_path, &destination) {
            remove_pending(&pending);
            return Err(format!(
                "failed to write {}: {error}",
                destination.display()
            ));
        }
        pending.remove(0);
    }
    Ok(())
}

fn validate_generated_destination(path: &Path) -> Result<(), String> {
    let metadata = match std::fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(format!("failed to inspect {}: {error}", path.display())),
    };
    if metadata.file_type().is_symlink() {
        return Err(format!(
            "{} is a symlink; refusing to replace an implicit output",
            path.display()
        ));
    }
    if !metadata.is_file() {
        return Err(format!(
            "{} exists and is not a regular generated file",
            path.display()
        ));
    }
    let existing = std::fs::read_to_string(path)
        .map_err(|error| format!("failed to validate existing {}: {error}", path.display()))?;
    if !existing.starts_with(GENERATED_MARKER) {
        return Err(format!(
            "{} already exists and was not generated by wasm_lite; move it or choose a different output path",
            path.display()
        ));
    }
    Ok(())
}

fn create_temporary_file(destination: &Path) -> Result<(PathBuf, std::fs::File), String> {
    let file_name = destination
        .file_name()
        .ok_or_else(|| format!("output path {} has no file name", destination.display()))?;
    for _ in 0..100 {
        let id = NEXT_TEMP_FILE.fetch_add(1, Ordering::Relaxed);
        let mut temporary_name = OsString::from(file_name);
        temporary_name.push(format!(".wasm_lite.tmp.{}.{}", std::process::id(), id));
        let temporary_path = destination.with_file_name(temporary_name);
        match std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary_path)
        {
            Ok(file) => return Ok((temporary_path, file)),
            Err(error) if error.kind() == ErrorKind::AlreadyExists => continue,
            Err(error) => {
                return Err(format!(
                    "failed to create temporary output beside {}: {error}",
                    destination.display()
                ));
            }
        }
    }
    Err(format!(
        "could not reserve a temporary output beside {}",
        destination.display()
    ))
}

fn remove_pending(pending: &[(PathBuf, PathBuf)]) {
    for (temporary_path, _) in pending {
        let _ = std::fs::remove_file(temporary_path);
    }
}
