//! Generate the JavaScript glue module from import descriptors.

use crate::descriptor::{AbiArg, Descriptor, Kind, Ret};
use crate::exports::{Export, ExportArg, ExportRet};
use std::fmt::Write;

const PREAMBLE: &str = "\
// Generated by wasm_lite_codegen — do not edit.
let __wl_memory;
let __wl_instance;

// Decode `len` UTF-8 bytes at `ptr` from the module's linear memory. A fresh
// view is taken each call so it stays valid if the module grows its memory.
function __wl_str(ptr, len) {
    return new TextDecoder(\"utf-8\").decode(new Uint8Array(__wl_memory.buffer, ptr, len));
}

// Copy a JS string into wasm memory for an export argument; returns [ptr, len].
// The caller frees it with __wl_free after the call.
function __wl_pass_str(s) {
    const bytes = new TextEncoder().encode(s);
    const ptr = __wl_instance.exports.__wl_malloc(bytes.length);
    new Uint8Array(__wl_memory.buffer, ptr, bytes.length).set(bytes);
    return [ptr, bytes.length];
}

// Value table: opaque handles to JS values. Rust holds an index; the table
// holds the real object. Freed slots are reused.
const __wl_heap = [];
const __wl_free = [];
function __wl_add(value) {
    const idx = __wl_free.length > 0 ? __wl_free.pop() : __wl_heap.length;
    __wl_heap[idx] = value;
    return idx;
}
function __wl_obj(idx) {
    return __wl_heap[idx];
}
function __wl_drop(idx) {
    __wl_heap[idx] = undefined;
    __wl_free.push(idx);
}

";

const INSTANTIATE: &str = "
export async function instantiate(wasmUrl) {
    const { instance } = await WebAssembly.instantiateStreaming(fetch(wasmUrl), makeImports());
    __wl_instance = instance;
    __wl_memory = instance.exports.memory;
    return instance;
}

// Used by the interop loader, which instantiates the merged module itself and
// then hands us the instance.
export function setInstance(instance) {
    __wl_instance = instance;
    __wl_memory = instance.exports.memory;
}
";

/// Generate the JS glue module for the given imports and exports.
///
/// The module exports `makeImports()` (the import object the wasm expects),
/// `instantiate(wasmUrl)` (fetch + instantiate), and one wrapper per
/// `#[wasm_lite::export]` function.
pub fn generate_glue(imports: &[Descriptor], exports: &[Export]) -> String {
    let mut js = String::from(PREAMBLE);
    js.push_str("export function makeImports() {\n    const imports = {};\n");
    // Runtime support: Rust calls this when a JsValue is dropped.
    js.push_str("    imports[\"__wasm_lite\"] = { __wl_drop: __wl_drop };\n");

    for d in imports {
        emit_shim(&mut js, d);
    }

    js.push_str("    return imports;\n}\n");
    js.push_str(INSTANTIATE);

    for export in exports {
        emit_export(&mut js, export);
    }
    js
}

/// Emit one export wrapper: a JS function that marshals `&str` args into wasm
/// memory, forwards to the export shim, frees, and unwraps the return.
fn emit_export(js: &mut String, export: &Export) {
    let params: Vec<String> = (0..export.args.len()).map(|i| format!("p{i}")).collect();

    let mut lines = Vec::new();
    let mut wasm_args = Vec::new();
    let mut frees = Vec::new();
    for (i, arg) in export.args.iter().enumerate() {
        match arg {
            ExportArg::Num => wasm_args.push(format!("p{i}")),
            ExportArg::Str => {
                lines.push(format!("const [__a{i}p, __a{i}l] = __wl_pass_str(p{i});"));
                wasm_args.push(format!("__a{i}p"));
                wasm_args.push(format!("__a{i}l"));
                frees.push(format!("__wl_instance.exports.__wl_free(__a{i}p, __a{i}l);"));
            }
        }
    }

    let call = format!(
        "__wl_instance.exports.__wl_export_{}({})",
        export.name,
        wasm_args.join(", ")
    );

    match export.ret {
        ExportRet::Void => {
            lines.push(format!("{call};"));
            lines.extend(frees);
        }
        ExportRet::Value => {
            lines.push(format!("const __ret = {call};"));
            lines.extend(frees);
            lines.push("return __ret;".into());
        }
        ExportRet::Bool => {
            lines.push(format!("const __ret = {call};"));
            lines.extend(frees);
            lines.push("return Boolean(__ret);".into());
        }
        ExportRet::Str => {
            lines.push(format!("const __ret = {call};"));
            lines.extend(frees);
            // The shim returns a packed i64 (BigInt in JS): (ptr << 32) | len.
            lines.push("const __packed = BigInt.asUintN(64, __ret);".into());
            lines.push("const __p = Number(__packed >> 32n), __l = Number(__packed & 0xffffffffn);".into());
            lines.push("const __s = __wl_str(__p, __l);".into());
            lines.push("__wl_instance.exports.__wl_free(__p, __l);".into());
            lines.push("return __s;".into());
        }
    }

    let _ = writeln!(
        js,
        "\nexport function {}({}) {{ {} }}",
        export.name,
        params.join(", "),
        lines.join(" ")
    );
}

/// Emit one import shim: a JS function that unmarshals wasm params and calls the
/// real JS function — `globalThis[ns][js_name](args)` for a function, or
/// `receiver[js_name](args)` for a method (whose first argument is the receiver).
fn emit_shim(js: &mut String, d: &Descriptor) {
    let ns = js_string(&d.namespace);
    let import_name = js_string(&d.import_name);
    let js_name = js_string(&d.js_name);

    // Build the wasm-level parameter list and the marshalled JS arguments. For a
    // method, the first (handle) argument is peeled off as the receiver.
    let mut params = Vec::new();
    let mut js_args = Vec::new();
    let mut receiver = None;

    for (i, arg) in d.args.iter().enumerate() {
        let is_receiver = d.kind == Kind::Method && i == 0;
        let marshalled = match arg {
            AbiArg::Str => {
                let ptr = next_param(&mut params);
                let len = next_param(&mut params);
                format!("__wl_str({ptr}, {len})")
            }
            AbiArg::Bool => format!("Boolean({})", next_param(&mut params)),
            AbiArg::Num => next_param(&mut params),
            AbiArg::Handle => format!("__wl_obj({})", next_param(&mut params)),
        };
        if is_receiver {
            receiver = Some(marshalled);
        } else {
            js_args.push(marshalled);
        }
    }

    let params = params.join(", ");
    let js_args = js_args.join(", ");

    let target = match d.kind {
        Kind::Function => format!("globalThis[{ns}][{js_name}]"),
        Kind::Method => format!("{}[{js_name}]", receiver.expect("method has a receiver")),
    };
    let call = format!("{target}({js_args})");

    // `imports[ns] ||= {}` then assign the shim, keyed on the wasm import name.
    let _ = writeln!(js, "    imports[{ns}] = imports[{ns}] || {{}};");
    match &d.ret {
        // A handle return stores the result in the value table and yields its index.
        Ret::Handle => {
            let _ = writeln!(js, "    imports[{ns}][{import_name}] = ({params}) => __wl_add({call});");
        }
        // A string return is copied into wasm memory; Rust takes ownership and frees.
        Ret::Str => {
            let _ = writeln!(
                js,
                "    imports[{ns}][{import_name}] = ({params}) => {{ \
                     const __r = {call}; \
                     const __b = new TextEncoder().encode(__r); \
                     const __p = __wl_instance.exports.__wl_malloc(__b.length); \
                     new Uint8Array(__wl_memory.buffer, __p, __b.length).set(__b); \
                     return (BigInt(__p) << 32n) | BigInt(__b.length); \
                 }};"
            );
        }
        Ret::Void | Ret::Value(_) => {
            let _ = writeln!(js, "    imports[{ns}][{import_name}] = ({params}) => {call};");
        }
    }
}

fn next_param(params: &mut Vec<String>) -> String {
    let p = format!("p{}", params.len());
    params.push(p.clone());
    p
}

/// Render a string as a double-quoted JS string literal.
fn js_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn func(ns: &str, import: &str, js: &str, args: Vec<AbiArg>, ret: Ret) -> Descriptor {
        Descriptor {
            kind: Kind::Function,
            namespace: ns.into(),
            import_name: import.into(),
            js_name: js.into(),
            args,
            ret,
        }
    }

    #[test]
    fn generates_str_and_numeric_shims() {
        let descriptors = vec![
            func("console", "log", "log", vec![AbiArg::Str], Ret::Void),
            func("performance", "now", "now", vec![], Ret::Value("f64".into())),
        ];
        let js = generate_glue(&descriptors, &[]);
        assert!(js.contains("imports[\"console\"][\"log\"] = (p0, p1) => globalThis[\"console\"][\"log\"](__wl_str(p0, p1));"));
        assert!(js.contains("imports[\"performance\"][\"now\"] = () => globalThis[\"performance\"][\"now\"]();"));
        assert!(js.contains("export async function instantiate"));
        // The value-table runtime import is always wired.
        assert!(js.contains("imports[\"__wasm_lite\"] = { __wl_drop: __wl_drop };"));
    }

    #[test]
    fn overload_keys_slot_on_import_name_but_calls_js_name() {
        let descriptors = vec![func(
            "Math",
            "max2",
            "max",
            vec![AbiArg::Num, AbiArg::Num],
            Ret::Value("f64".into()),
        )];
        let js = generate_glue(&descriptors, &[]);
        assert!(js.contains(
            "imports[\"Math\"][\"max2\"] = (p0, p1) => globalThis[\"Math\"][\"max\"](p0, p1);"
        ));
    }

    #[test]
    fn handle_return_is_added_to_the_table() {
        let descriptors = vec![func(
            "JSON",
            "parse",
            "parse",
            vec![AbiArg::Str],
            Ret::Handle,
        )];
        let js = generate_glue(&descriptors, &[]);
        assert!(js.contains(
            "imports[\"JSON\"][\"parse\"] = (p0, p1) => __wl_add(globalThis[\"JSON\"][\"parse\"](__wl_str(p0, p1)));"
        ));
    }

    #[test]
    fn method_calls_through_the_receiver_handle() {
        let descriptors = vec![Descriptor {
            kind: Kind::Method,
            namespace: "Array".into(),
            import_name: "push".into(),
            js_name: "push".into(),
            args: vec![AbiArg::Handle, AbiArg::Num],
            ret: Ret::Value("f64".into()),
        }];
        let js = generate_glue(&descriptors, &[]);
        assert!(js.contains(
            "imports[\"Array\"][\"push\"] = (p0, p1) => __wl_obj(p0)[\"push\"](p1);"
        ));
    }

    #[test]
    fn generates_export_wrappers() {
        let exports = vec![
            Export { name: "add".into(), args: vec![ExportArg::Num, ExportArg::Num], ret: ExportRet::Value },
            Export { name: "is_even".into(), args: vec![ExportArg::Num], ret: ExportRet::Bool },
            Export { name: "tick".into(), args: vec![], ret: ExportRet::Void },
        ];
        let js = generate_glue(&[], &exports);
        assert!(js.contains("export function add(p0, p1) { const __ret = __wl_instance.exports.__wl_export_add(p0, p1); return __ret; }"));
        assert!(js.contains("export function is_even(p0) { const __ret = __wl_instance.exports.__wl_export_is_even(p0); return Boolean(__ret); }"));
        assert!(js.contains("export function tick() { __wl_instance.exports.__wl_export_tick(); }"));
    }

    #[test]
    fn generates_string_export_wrapper() {
        let exports = vec![Export {
            name: "greet".into(),
            args: vec![ExportArg::Str],
            ret: ExportRet::Str,
        }];
        let js = generate_glue(&[], &exports);
        assert!(js.contains("const [__a0p, __a0l] = __wl_pass_str(p0);"));
        assert!(js.contains("__wl_instance.exports.__wl_export_greet(__a0p, __a0l)"));
        assert!(js.contains("__wl_instance.exports.__wl_free(__a0p, __a0l);"));
        assert!(js.contains("const __s = __wl_str(__p, __l);"));
    }
}
