//! Generate the JavaScript glue module from import descriptors.

use crate::descriptor::{AbiArg, Descriptor};
use std::fmt::Write;

const PREAMBLE: &str = "\
// Generated by wasm_lite_codegen — do not edit.
let __wl_memory;

// Decode `len` UTF-8 bytes at `ptr` from the module's linear memory. A fresh
// view is taken each call so it stays valid if the module grows its memory.
function __wl_str(ptr, len) {
    return new TextDecoder(\"utf-8\").decode(new Uint8Array(__wl_memory.buffer, ptr, len));
}

";

const INSTANTIATE: &str = "
export async function instantiate(wasmUrl) {
    const { instance } = await WebAssembly.instantiateStreaming(fetch(wasmUrl), makeImports());
    __wl_memory = instance.exports.memory;
    return instance;
}
";

/// Generate the JS glue module for the given imports.
///
/// The module exports `makeImports()` (the import object the wasm expects) and
/// `instantiate(wasmUrl)` (fetch + instantiate, returning the instance).
pub fn generate_glue(descriptors: &[Descriptor]) -> String {
    let mut js = String::from(PREAMBLE);
    js.push_str("export function makeImports() {\n    const imports = {};\n");

    for d in descriptors {
        emit_shim(&mut js, d);
    }

    js.push_str("    return imports;\n}\n");
    js.push_str(INSTANTIATE);
    js
}

/// Emit one import shim: a JS function that unmarshals wasm params and calls
/// the real `globalThis[namespace][name]`.
fn emit_shim(js: &mut String, d: &Descriptor) {
    let ns = js_string(&d.namespace);
    let name = js_string(&d.name);

    // Build the wasm-level parameter list and the marshalled JS arguments.
    let mut params = Vec::new();
    let mut js_args = Vec::new();
    for arg in &d.args {
        match arg {
            AbiArg::Str => {
                let ptr = next_param(&mut params);
                let len = next_param(&mut params);
                js_args.push(format!("__wl_str({ptr}, {len})"));
            }
            AbiArg::Bool => {
                let p = next_param(&mut params);
                js_args.push(format!("Boolean({p})"));
            }
            AbiArg::Num => {
                let p = next_param(&mut params);
                js_args.push(p);
            }
        }
    }

    let params = params.join(", ");
    let js_args = js_args.join(", ");

    // `imports[ns] ||= {}` then assign the shim.
    let _ = writeln!(js, "    imports[{ns}] = imports[{ns}] || {{}};");
    let _ = writeln!(
        js,
        "    imports[{ns}][{name}] = ({params}) => globalThis[{ns}][{name}]({js_args});"
    );
}

fn next_param(params: &mut Vec<String>) -> String {
    let p = format!("p{}", params.len());
    params.push(p.clone());
    p
}

/// Render a string as a double-quoted JS string literal.
fn js_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_str_and_numeric_shims() {
        let descriptors = vec![
            Descriptor {
                namespace: "console".into(),
                name: "log".into(),
                args: vec![AbiArg::Str],
                ret: None,
            },
            Descriptor {
                namespace: "performance".into(),
                name: "now".into(),
                args: vec![],
                ret: Some("f64".into()),
            },
        ];
        let js = generate_glue(&descriptors);
        assert!(js.contains("imports[\"console\"][\"log\"] = (p0, p1) => globalThis[\"console\"][\"log\"](__wl_str(p0, p1));"));
        assert!(js.contains("imports[\"performance\"][\"now\"] = () => globalThis[\"performance\"][\"now\"]();"));
        assert!(js.contains("export async function instantiate"));
    }
}
