//! Generate the JavaScript glue module from import descriptors.

use crate::descriptor::{AbiArg, Descriptor, Kind, Ret};
use crate::exports::{Export, ExportArg, ExportRet, Payload};
use std::fmt::Write;

const PREAMBLE: &str = "\
// Generated by wasm_lite_codegen — do not edit.
let __wl_memory;
let __wl_instance;

// Decode `len` UTF-8 bytes at `ptr` from the module's linear memory. A fresh
// view is taken each call so it stays valid if the module grows its memory.
function __wl_str(ptr, len) {
    return new TextDecoder(\"utf-8\").decode(new Uint8Array(__wl_memory.buffer, ptr, len));
}

// Copy a JS string into wasm memory for an export argument; returns [ptr, len].
// The caller frees it with __wl_free after the call.
function __wl_pass_str(s) {
    const bytes = new TextEncoder().encode(s);
    const ptr = __wl_instance.exports.__wl_malloc(bytes.length);
    new Uint8Array(__wl_memory.buffer, ptr, bytes.length).set(bytes);
    return [ptr, bytes.length];
}

// Copy bytes into wasm memory for an export argument; returns [ptr, len]. Accepts
// a Uint8Array (or anything Uint8Array's constructor coerces, e.g. a number[]).
function __wl_pass_bytes(a) {
    const bytes = a instanceof Uint8Array ? a : new Uint8Array(a);
    const ptr = __wl_instance.exports.__wl_malloc(bytes.length);
    new Uint8Array(__wl_memory.buffer, ptr, bytes.length).set(bytes);
    return [ptr, bytes.length];
}

// Value table: opaque handles to JS values. Rust holds an index; the table
// holds the real object. Freed slots are reused.
const __wl_heap = [];
const __wl_free = [];
function __wl_add(value) {
    const idx = __wl_free.length > 0 ? __wl_free.pop() : __wl_heap.length;
    __wl_heap[idx] = value;
    return idx;
}
function __wl_obj(idx) {
    return __wl_heap[idx];
}
function __wl_drop(idx) {
    __wl_heap[idx] = undefined;
    __wl_free.push(idx);
}

";

const INSTANTIATE: &str = "
export async function instantiate(wasmUrl) {
    const { instance } = await WebAssembly.instantiateStreaming(fetch(wasmUrl), makeImports());
    __wl_instance = instance;
    __wl_memory = instance.exports.memory;
    return instance;
}

// Used by the interop loader, which instantiates the merged module itself and
// then hands us the instance.
export function setInstance(instance) {
    __wl_instance = instance;
    __wl_memory = instance.exports.memory;
}
";

/// Generate the JS glue module for the given imports and exports.
///
/// The module exports `makeImports()` (the import object the wasm expects),
/// `instantiate(wasmUrl)` (fetch + instantiate), and one wrapper per
/// `#[wasm_lite::export]` function.
pub fn generate_glue(imports: &[Descriptor], exports: &[Export]) -> String {
    let mut js = String::from(PREAMBLE);
    js.push_str("export function makeImports() {\n    const imports = {};\n");
    // Runtime support: Rust calls this when a JsValue is dropped.
    js.push_str("    imports[\"__wasm_lite\"] = { __wl_drop: __wl_drop };\n");

    for d in imports {
        emit_shim(&mut js, d);
    }

    js.push_str("    return imports;\n}\n");
    js.push_str(INSTANTIATE);

    for export in exports {
        emit_export(&mut js, export);
    }
    js
}

/// Emit one export wrapper: a JS function that marshals `&str` args into wasm
/// memory, forwards to the export shim, frees, and unwraps the return.
fn emit_export(js: &mut String, export: &Export) {
    let params: Vec<String> = (0..export.args.len()).map(|i| format!("p{i}")).collect();

    let mut lines = Vec::new();
    let mut wasm_args = Vec::new();
    let mut frees = Vec::new();
    for (i, arg) in export.args.iter().enumerate() {
        match arg {
            ExportArg::Num => wasm_args.push(format!("p{i}")),
            ExportArg::Str => {
                lines.push(format!("const [__a{i}p, __a{i}l] = __wl_pass_str(p{i});"));
                wasm_args.push(format!("__a{i}p"));
                wasm_args.push(format!("__a{i}l"));
                frees.push(format!("__wl_instance.exports.__wl_free(__a{i}p, __a{i}l);"));
            }
            ExportArg::Bytes => {
                lines.push(format!("const [__a{i}p, __a{i}l] = __wl_pass_bytes(p{i});"));
                wasm_args.push(format!("__a{i}p"));
                wasm_args.push(format!("__a{i}l"));
                frees.push(format!("__wl_instance.exports.__wl_free(__a{i}p, __a{i}l);"));
            }
            ExportArg::Handle => {
                // Register the object; Rust owns the handle and frees the slot
                // itself when its JsValue drops, so JS does not free it here.
                lines.push(format!("const __a{i}h = __wl_add(p{i});"));
                wasm_args.push(format!("__a{i}h"));
            }
        }
    }

    let call = format!(
        "__wl_instance.exports.__wl_export_{}({})",
        export.name,
        wasm_args.join(", ")
    );

    match export.ret {
        ExportRet::Void => {
            lines.push(format!("{call};"));
            lines.extend(frees);
        }
        ExportRet::Value => {
            lines.push(format!("const __ret = {call};"));
            lines.extend(frees);
            lines.push("return __ret;".into());
        }
        ExportRet::Bool => {
            lines.push(format!("const __ret = {call};"));
            lines.extend(frees);
            lines.push("return Boolean(__ret);".into());
        }
        ExportRet::Str => {
            lines.push(format!("const __ret = {call};"));
            lines.extend(frees);
            // The shim returns a packed i64 (BigInt in JS): (ptr << 32) | len.
            lines.push("const __packed = BigInt.asUintN(64, __ret);".into());
            lines.push("const __p = Number(__packed >> 32n), __l = Number(__packed & 0xffffffffn);".into());
            lines.push("const __s = __wl_str(__p, __l);".into());
            lines.push("__wl_instance.exports.__wl_free(__p, __l);".into());
            lines.push("return __s;".into());
        }
        ExportRet::Bytes => {
            lines.push(format!("const __ret = {call};"));
            lines.extend(frees);
            lines.push("const __packed = BigInt.asUintN(64, __ret);".into());
            lines.push("const __p = Number(__packed >> 32n), __l = Number(__packed & 0xffffffffn);".into());
            // Copy out of wasm memory before freeing (a view would dangle after free).
            lines.push("const __b = new Uint8Array(__wl_memory.buffer, __p, __l).slice();".into());
            lines.push("__wl_instance.exports.__wl_free(__p, __l);".into());
            lines.push("return __b;".into());
        }
        ExportRet::Handle => {
            lines.push(format!("const __idx = {call};"));
            lines.extend(frees);
            // Rust transferred ownership (it `forget`s the JsValue); read the
            // object out, free the now-orphaned table slot, and hand it to JS.
            lines.push("const __o = __wl_obj(__idx);".into());
            lines.push("__wl_drop(__idx);".into());
            lines.push("return __o;".into());
        }
        // sret returns: Rust wrote a discriminant at __ret and a payload at
        // __ret+8. The buffer is the export's leading argument.
        ExportRet::Opt(p) => {
            let sret_call = sret_call(&export.name, &wasm_args);
            lines.push("const __ret = __wl_instance.exports.__wl_malloc(16);".into());
            lines.push(format!("{sret_call};"));
            lines.extend(frees);
            lines.push("const __dv = new DataView(__wl_memory.buffer);".into());
            lines.push("let __result;".into());
            lines.push("if (__dv.getUint32(__ret, true) === 1) {".into());
            let (stmts, expr) = read_payload(p, "__ret + 8", "v");
            for s in stmts {
                lines.push(format!("    {s}"));
            }
            lines.push(format!("    __result = {expr};"));
            lines.push("} else { __result = null; }".into());
            lines.push("__wl_instance.exports.__wl_free(__ret, 16);".into());
            lines.push("return __result;".into());
        }
        ExportRet::Res(ok, err) => {
            let sret_call = sret_call(&export.name, &wasm_args);
            lines.push("const __ret = __wl_instance.exports.__wl_malloc(16);".into());
            lines.push(format!("{sret_call};"));
            lines.extend(frees);
            lines.push("const __dv = new DataView(__wl_memory.buffer);".into());
            lines.push("const __tag = __dv.getUint32(__ret, true);".into());
            lines.push("if (__tag === 0) {".into());
            let (ok_stmts, ok_expr) = read_payload(ok, "__ret + 8", "ok");
            for s in ok_stmts {
                lines.push(format!("    {s}"));
            }
            lines.push(format!("    const __okv = {ok_expr};"));
            lines.push("    __wl_instance.exports.__wl_free(__ret, 16);".into());
            lines.push("    return __okv;".into());
            lines.push("} else {".into());
            let (err_stmts, err_expr) = read_payload(err, "__ret + 8", "err");
            for s in err_stmts {
                lines.push(format!("    {s}"));
            }
            lines.push(format!("    const __errv = {err_expr};"));
            lines.push("    __wl_instance.exports.__wl_free(__ret, 16);".into());
            lines.push("    throw __errv;".into());
            lines.push("}".into());
        }
    }

    let _ = writeln!(
        js,
        "\nexport function {}({}) {{ {} }}",
        export.name,
        params.join(", "),
        lines.join(" ")
    );
}

/// The export call for an sret return: the buffer `__ret` is the leading argument.
fn sret_call(name: &str, wasm_args: &[String]) -> String {
    let mut args = vec!["__ret".to_string()];
    args.extend(wasm_args.iter().cloned());
    format!("__wl_instance.exports.__wl_export_{name}({})", args.join(", "))
}

/// Read one sret payload from the buffer at JS offset `off`. Returns the
/// statements to run (using a `__dv` DataView already in scope) and the final
/// value expression. `sfx` disambiguates locals between Ok/Err payloads.
fn read_payload(p: Payload, off: &str, sfx: &str) -> (Vec<String>, String) {
    match p {
        Payload::I32 => (vec![], format!("__dv.getInt32({off}, true)")),
        Payload::U32 => (vec![], format!("__dv.getUint32({off}, true)")),
        Payload::F64 => (vec![], format!("__dv.getFloat64({off}, true)")),
        Payload::Bool => (vec![], format!("Boolean(__dv.getInt32({off}, true))")),
        Payload::Handle => (
            vec![format!(
                "const __h_{sfx} = __dv.getUint32({off}, true); const __o_{sfx} = __wl_obj(__h_{sfx}); __wl_drop(__h_{sfx});"
            )],
            format!("__o_{sfx}"),
        ),
        Payload::Str => (
            vec![format!(
                "const __p_{sfx} = __dv.getUint32({off}, true), __l_{sfx} = __dv.getUint32(({off}) + 4, true); \
                 const __s_{sfx} = __wl_str(__p_{sfx}, __l_{sfx}); __wl_instance.exports.__wl_free(__p_{sfx}, __l_{sfx});"
            )],
            format!("__s_{sfx}"),
        ),
        Payload::Bytes => (
            vec![format!(
                "const __p_{sfx} = __dv.getUint32({off}, true), __l_{sfx} = __dv.getUint32(({off}) + 4, true); \
                 const __b_{sfx} = new Uint8Array(__wl_memory.buffer, __p_{sfx}, __l_{sfx}).slice(); \
                 __wl_instance.exports.__wl_free(__p_{sfx}, __l_{sfx});"
            )],
            format!("__b_{sfx}"),
        ),
    }
}

/// Write `val` (of payload type `p`) into the sret buffer at JS offset `off`.
/// Returns `(prep, set)`: `prep` runs first (may `malloc`, which can grow memory
/// and detach views); `set` runs after a fresh `__dv` DataView is created.
fn write_payload(p: Payload, off: &str, val: &str) -> (Vec<String>, Vec<String>) {
    match p {
        Payload::I32 => (vec![], vec![format!("__dv.setInt32({off}, {val}, true);")]),
        Payload::U32 => (vec![], vec![format!("__dv.setUint32({off}, {val}, true);")]),
        Payload::F64 => (vec![], vec![format!("__dv.setFloat64({off}, {val}, true);")]),
        Payload::Bool => (vec![], vec![format!("__dv.setInt32({off}, ({val}) ? 1 : 0, true);")]),
        Payload::Handle => (
            vec![format!("const __wh = __wl_add({val});")],
            vec![format!("__dv.setUint32({off}, __wh, true);")],
        ),
        Payload::Str => (
            vec![format!(
                "const __wb = new TextEncoder().encode({val}); \
                 const __wp = __wl_instance.exports.__wl_malloc(__wb.length); \
                 new Uint8Array(__wl_memory.buffer, __wp, __wb.length).set(__wb);"
            )],
            vec![format!("__dv.setUint32({off}, __wp, true); __dv.setUint32(({off}) + 4, __wb.length, true);")],
        ),
        Payload::Bytes => (
            vec![format!(
                "const __wb = ({val} instanceof Uint8Array ? {val} : new Uint8Array({val})); \
                 const __wp = __wl_instance.exports.__wl_malloc(__wb.length); \
                 new Uint8Array(__wl_memory.buffer, __wp, __wb.length).set(__wb);"
            )],
            vec![format!("__dv.setUint32({off}, __wp, true); __dv.setUint32(({off}) + 4, __wb.length, true);")],
        ),
    }
}

/// Emit one import shim: a JS function that unmarshals wasm params and calls the
/// real JS function — `globalThis[ns][js_name](args)` for a function, or
/// `receiver[js_name](args)` for a method (whose first argument is the receiver).
fn emit_shim(js: &mut String, d: &Descriptor) {
    let ns = js_string(&d.namespace);
    let import_name = js_string(&d.import_name);
    let js_name = js_string(&d.js_name);

    // Build the wasm-level parameter list and the marshalled JS arguments. For a
    // method, the first (handle) argument is peeled off as the receiver.
    let mut params = Vec::new();
    let mut js_args = Vec::new();
    let mut receiver = None;

    for (i, arg) in d.args.iter().enumerate() {
        let is_receiver = d.kind == Kind::Method && i == 0;
        let marshalled = match arg {
            AbiArg::Str => {
                let ptr = next_param(&mut params);
                let len = next_param(&mut params);
                format!("__wl_str({ptr}, {len})")
            }
            AbiArg::Bytes => {
                // A transient view into wasm memory — valid for the call's duration.
                let ptr = next_param(&mut params);
                let len = next_param(&mut params);
                format!("new Uint8Array(__wl_memory.buffer, {ptr}, {len})")
            }
            AbiArg::Bool => format!("Boolean({})", next_param(&mut params)),
            AbiArg::Num => next_param(&mut params),
            AbiArg::Handle => format!("__wl_obj({})", next_param(&mut params)),
        };
        if is_receiver {
            receiver = Some(marshalled);
        } else {
            js_args.push(marshalled);
        }
    }

    let params = params.join(", ");
    let js_args = js_args.join(", ");

    let target = match d.kind {
        Kind::Function => format!("globalThis[{ns}][{js_name}]"),
        Kind::Method => format!("{}[{js_name}]", receiver.expect("method has a receiver")),
    };
    let call = format!("{target}({js_args})");

    // `imports[ns] ||= {}` then assign the shim, keyed on the wasm import name.
    let _ = writeln!(js, "    imports[{ns}] = imports[{ns}] || {{}};");
    match &d.ret {
        // A handle return stores the result in the value table and yields its index.
        Ret::Handle => {
            let _ = writeln!(js, "    imports[{ns}][{import_name}] = ({params}) => __wl_add({call});");
        }
        // A string return is copied into wasm memory; Rust takes ownership and frees.
        Ret::Str => {
            let _ = writeln!(
                js,
                "    imports[{ns}][{import_name}] = ({params}) => {{ \
                     const __r = {call}; \
                     const __b = new TextEncoder().encode(__r); \
                     const __p = __wl_instance.exports.__wl_malloc(__b.length); \
                     new Uint8Array(__wl_memory.buffer, __p, __b.length).set(__b); \
                     return (BigInt(__p) << 32n) | BigInt(__b.length); \
                 }};"
            );
        }
        // A bytes return: coerce to a Uint8Array, copy into wasm memory, hand off.
        Ret::Bytes => {
            let _ = writeln!(
                js,
                "    imports[{ns}][{import_name}] = ({params}) => {{ \
                     const __r = {call}; \
                     const __b = __r instanceof Uint8Array ? __r : new Uint8Array(__r); \
                     const __p = __wl_instance.exports.__wl_malloc(__b.length); \
                     new Uint8Array(__wl_memory.buffer, __p, __b.length).set(__b); \
                     return (BigInt(__p) << 32n) | BigInt(__b.length); \
                 }};"
            );
        }
        // sret returns: the shim writes a discriminant + payload into a leading
        // retptr buffer rather than returning a value.
        Ret::Opt(p) => {
            let shim_params = if params.is_empty() { "__retp".to_string() } else { format!("__retp, {params}") };
            let (prep, set) = write_payload(*p, "__retp + 8", "__r");
            let body = format!(
                "const __r = {call}; \
                 if (__r === null || __r === undefined) {{ new DataView(__wl_memory.buffer).setUint32(__retp, 0, true); }} \
                 else {{ {prep} const __dv = new DataView(__wl_memory.buffer); __dv.setUint32(__retp, 1, true); {set} }}",
                prep = prep.join(" "),
                set = set.join(" "),
            );
            let _ = writeln!(js, "    imports[{ns}][{import_name}] = ({shim_params}) => {{ {body} }};");
        }
        Ret::Res(ok, err) => {
            let shim_params = if params.is_empty() { "__retp".to_string() } else { format!("__retp, {params}") };
            let (ok_prep, ok_set) = write_payload(*ok, "__retp + 8", "__r");
            let (err_prep, err_set) = write_payload(*err, "__retp + 8", "__e");
            let body = format!(
                "try {{ const __r = {call}; {ok_prep} const __dv = new DataView(__wl_memory.buffer); \
                 __dv.setUint32(__retp, 0, true); {ok_set} }} \
                 catch (__e) {{ {err_prep} const __dv = new DataView(__wl_memory.buffer); \
                 __dv.setUint32(__retp, 1, true); {err_set} }}",
                ok_prep = ok_prep.join(" "),
                ok_set = ok_set.join(" "),
                err_prep = err_prep.join(" "),
                err_set = err_set.join(" "),
            );
            let _ = writeln!(js, "    imports[{ns}][{import_name}] = ({shim_params}) => {{ {body} }};");
        }
        Ret::Void | Ret::Value(_) => {
            let _ = writeln!(js, "    imports[{ns}][{import_name}] = ({params}) => {call};");
        }
    }
}

fn next_param(params: &mut Vec<String>) -> String {
    let p = format!("p{}", params.len());
    params.push(p.clone());
    p
}

/// Render a string as a double-quoted JS string literal.
fn js_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn func(ns: &str, import: &str, js: &str, args: Vec<AbiArg>, ret: Ret) -> Descriptor {
        Descriptor {
            kind: Kind::Function,
            namespace: ns.into(),
            import_name: import.into(),
            js_name: js.into(),
            args,
            ret,
        }
    }

    #[test]
    fn generates_str_and_numeric_shims() {
        let descriptors = vec![
            func("console", "log", "log", vec![AbiArg::Str], Ret::Void),
            func("performance", "now", "now", vec![], Ret::Value("f64".into())),
        ];
        let js = generate_glue(&descriptors, &[]);
        assert!(js.contains("imports[\"console\"][\"log\"] = (p0, p1) => globalThis[\"console\"][\"log\"](__wl_str(p0, p1));"));
        assert!(js.contains("imports[\"performance\"][\"now\"] = () => globalThis[\"performance\"][\"now\"]();"));
        assert!(js.contains("export async function instantiate"));
        // The value-table runtime import is always wired.
        assert!(js.contains("imports[\"__wasm_lite\"] = { __wl_drop: __wl_drop };"));
    }

    #[test]
    fn overload_keys_slot_on_import_name_but_calls_js_name() {
        let descriptors = vec![func(
            "Math",
            "max2",
            "max",
            vec![AbiArg::Num, AbiArg::Num],
            Ret::Value("f64".into()),
        )];
        let js = generate_glue(&descriptors, &[]);
        assert!(js.contains(
            "imports[\"Math\"][\"max2\"] = (p0, p1) => globalThis[\"Math\"][\"max\"](p0, p1);"
        ));
    }

    #[test]
    fn handle_return_is_added_to_the_table() {
        let descriptors = vec![func(
            "JSON",
            "parse",
            "parse",
            vec![AbiArg::Str],
            Ret::Handle,
        )];
        let js = generate_glue(&descriptors, &[]);
        assert!(js.contains(
            "imports[\"JSON\"][\"parse\"] = (p0, p1) => __wl_add(globalThis[\"JSON\"][\"parse\"](__wl_str(p0, p1)));"
        ));
    }

    #[test]
    fn method_calls_through_the_receiver_handle() {
        let descriptors = vec![Descriptor {
            kind: Kind::Method,
            namespace: "Array".into(),
            import_name: "push".into(),
            js_name: "push".into(),
            args: vec![AbiArg::Handle, AbiArg::Num],
            ret: Ret::Value("f64".into()),
        }];
        let js = generate_glue(&descriptors, &[]);
        assert!(js.contains(
            "imports[\"Array\"][\"push\"] = (p0, p1) => __wl_obj(p0)[\"push\"](p1);"
        ));
    }

    #[test]
    fn generates_export_wrappers() {
        let exports = vec![
            Export { name: "add".into(), args: vec![ExportArg::Num, ExportArg::Num], ret: ExportRet::Value },
            Export { name: "is_even".into(), args: vec![ExportArg::Num], ret: ExportRet::Bool },
            Export { name: "tick".into(), args: vec![], ret: ExportRet::Void },
        ];
        let js = generate_glue(&[], &exports);
        assert!(js.contains("export function add(p0, p1) { const __ret = __wl_instance.exports.__wl_export_add(p0, p1); return __ret; }"));
        assert!(js.contains("export function is_even(p0) { const __ret = __wl_instance.exports.__wl_export_is_even(p0); return Boolean(__ret); }"));
        assert!(js.contains("export function tick() { __wl_instance.exports.__wl_export_tick(); }"));
    }

    #[test]
    fn generates_string_export_wrapper() {
        let exports = vec![Export {
            name: "greet".into(),
            args: vec![ExportArg::Str],
            ret: ExportRet::Str,
        }];
        let js = generate_glue(&[], &exports);
        assert!(js.contains("const [__a0p, __a0l] = __wl_pass_str(p0);"));
        assert!(js.contains("__wl_instance.exports.__wl_export_greet(__a0p, __a0l)"));
        assert!(js.contains("__wl_instance.exports.__wl_free(__a0p, __a0l);"));
        assert!(js.contains("const __s = __wl_str(__p, __l);"));
    }
}
