//! Interop bridge between [`crate::JsValue`] and `wasm_bindgen::JsValue`.
//!
//! Both crates manage JS objects through their own value tables, so a handle
//! from one is meaningless to the other. This module converts between them with
//! an explicit, ownership-consuming step. The trick: neither side touches the
//! other's table internals. Each uses its *own* marshalling to hand the object
//! through a neutral global slot (`globalThis.__wlbridge`), which the interop
//! loader (generated by `wasm_lite_codegen`) defines.
//!
//! A conversion is a *move*: the source handle is consumed (its table slot
//! freed) and a new handle owning the other table's slot is produced. The
//! shared slot keeps the object rooted during the handoff, so it is never
//! momentarily unreachable — no double-free, no leak.

use crate::JsValue as WlValue;
use wasm_bindgen::JsValue as WbValue;

// wasm_lite side of the handoff (our marshalling: `&JsValue` / `-> JsValue`).
mod wl_bridge {
    use crate::JsValue;
    crate::import! {
        "__wlbridge" {
            fn put(v: &JsValue);
            fn take() -> JsValue;
        }
    }
}

// wasm-bindgen side of the handoff (its marshalling, via bare globals).
mod wb_bridge {
    use wasm_bindgen::prelude::*;
    #[wasm_bindgen]
    extern "C" {
        #[wasm_bindgen(js_name = __wlbridge_put_wb)]
        pub fn put(v: JsValue);
        #[wasm_bindgen(js_name = __wlbridge_take_wb)]
        pub fn take() -> JsValue;
    }
}

/// Convert a `wasm_lite` handle into a `wasm_bindgen` handle, consuming `self`.
pub trait ToWasmBindgen {
    fn to_wasm_bindgen(self) -> WbValue;
}

impl ToWasmBindgen for WlValue {
    fn to_wasm_bindgen(self) -> WbValue {
        wl_bridge::put(&self); // our table -> shared slot
        drop(self); // free our slot (object stays rooted via the slot)
        wb_bridge::take() // shared slot -> wasm-bindgen's table
    }
}

/// Convert a `wasm_bindgen` handle into a `wasm_lite` handle, consuming `self`.
pub trait ToWasmLite {
    fn to_wasm_lite(self) -> WlValue;
}

impl ToWasmLite for WbValue {
    fn to_wasm_lite(self) -> WlValue {
        wb_bridge::put(self); // by value: wasm-bindgen frees its slot, object -> shared slot
        wl_bridge::take() // shared slot -> our table
    }
}
