#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo "fmt check"
scripts/fmt
echo "check"
scripts/check "$@"
echo "clippy"
scripts/clippy "$@"
echo "tests"
scripts/tests "$@"
echo "docs"
scripts/docs "$@"
