#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../.."

WARN_FLAGS="-D warnings"
if [[ " $* " =~ " --relaxed " ]]; then
    WARN_FLAGS=""
fi

RUSTDOCFLAGS="$WARN_FLAGS" cargo doc --workspace --no-deps --lib
