[package]
name = "runner"
description = "Serves a wasm_lite program over local HTTP and opens it in the default browser."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
wasm_lite_codegen = { path = "../crates/wasm_lite_codegen" }
